---
title: "Volcano Plot - Alain - A vs B"
author: "Benjamin Vittrant"
date: "March 26, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cargement des données

```{r}
d = read.table(file='AvsB.tsv', header=T, sep='\t', dec = ',')

```

On vérifie les noms des colonnes:

```{r}
colnames(d)
```

## Volcano plot

```{r}
#basique volcano plot
with(d, plot(log2FoldChange, -log10(padj), pch=20, main="Volcano plot", 
             xlim = c(-8,8),
             xlab = 'log2FoldChange', ylab='pval adjusted'))

# Add colored points: red if padj<0.05, orange of log2FC>1, green if both)
with(subset(d, padj<.05 ), points(log2FoldChange, -log10(padj), 
                                  pch=20, col="red"))

with(subset(d, abs(log2FoldChange)>1), points(log2FoldChange,-log10(padj)
                                  , pch=20, col="orange"))

with(subset(d, padj<.05 & abs(log2FoldChange)>1),
     points(log2FoldChange,-log10(padj), pch=20, col="green"))

# Label points with the textxy function from the calibrate plot
library(calibrate)
with(subset(d, padj<.05 & abs(log2FoldChange)>1),
     textxy(log2FoldChange, -log10(padj), labs=symbol, cex=.8))
abline(h=-log10(0.05), v=c(-1,1))

```

On voit que le point Ogn décale tout. Je refais un plot en enlevant ce point.

```{r}

d2 = d[which(d$symbol != 'Ogn'),]
#basique volcano plot
with(d2, plot(log2FoldChange, -log10(padj), pch=20, main="Volcano plot",
              xlim = c(-8,8),
              xlab = 'log2FoldChange', ylab='pval adjusted'))

# Add colored points: red if padj<0.05, orange of log2FC>1, green if both)
with(subset(d2, padj<.05 ), points(log2FoldChange, -log10(padj),
              pch=20, col="red"))

with(subset(d2, abs(log2FoldChange)>1), points(log2FoldChange, -log10(padj),
              pch=20, col="orange"))

with(subset(d2, padj<.05 & abs(log2FoldChange)>1),
            points(log2FoldChange,-log10(padj), pch=20, col="green"))

# Label points with the textxy function from the calibrate plot
library(calibrate)
with(subset(d2, padj<.05 & abs(log2FoldChange)>1), 
     textxy(log2FoldChange, -log10(padj), labs=symbol, cex=.8))

abline(h=-log10(0.05), v=c(-1,1))

```

